mutation Missing_people(
	$applicant_name: String!
	$applicant_phone: Int!
	$missing_person_name: String!
	$missing_person_gender: Int!
	$missing_person_phone: Int!
	$birthdate: String
	$search_area_type: Int!
	$disappearance_circumstances: String
	$health_state: String!
	$loss_area: Int
	$missing_persons_clothes: String
	$special_signs: String!
	$missing_person_have: String
	$loss_address: String
	$special_items: String!
	$additional_information: String
	$loss_date: String!
	$loss_time: String
	$relatives_contacts: Int
	$image: String
	$police_application: String
	$additional_loss_area: Int
) {
	missing_people {
		create(
			applicant_name: $applicant_name
			applicant_phone: $applicant_phone
			missing_person_name: $missing_person_name
			missing_person_gender: $missing_person_gender
			missing_person_phone: $missing_person_phone
			birthdate: $birthdate
			search_area_type: $search_area_type
			disappearance_circumstances: $disappearance_circumstances
			health_state: $health_state
			loss_area: $loss_area
			missing_persons_clothes: $missing_persons_clothes
			special_signs: $special_signs
			missing_person_have: $missing_person_have
			loss_address: $loss_address
			special_items: $special_items
			additional_information: $additional_information
			loss_date: $loss_date
			loss_time: $loss_time
			relatives_contacts: $relatives_contacts
			image: $image
			police_application: $police_application
			additional_loss_area: $additional_loss_area
		) {
			... on MissingPeople {
				applicant_name
				applicant_phone
				missing_person_name
				missing_person_gender
				missing_person_phone
				birthdate
				search_area_type
				disappearance_circumstances
				health_state
				loss_area
				missing_persons_clothes
				special_signs
				missing_person_have
				loss_address
				special_items
				additional_information
				loss_date
				loss_time
				relatives_contacts
				additional_loss_area
				image
				police_application
			}
			... on ValidationErrorsList {
				errors {
					field
					messages
				}
			}
		}
	}
}
