mutation Missing_people(
	$applicant_full_name: String!
	$applicant_phone: Int!
	$missing_full_name: String!
	$missing_gender: Int!
	$missing_phone: Int
	$missing_dob: String
	$search_area_type: Int!
	$circumstances_of_missing: String
	$missing_health: String!
	$missing_region: Int
	$missing_clothes: String
	$missing_special_features: String!
	$missing_carry_item: String
	$missing_address: String
	$additional_info: String
	$missing_date: String!
	$missing_time: String
	$family_contacts: String
	$upload_photo: String
	$police_report: String
	$additional_area_of_search: String
) {
	missing_people {
		create(
			applicant_full_name: $applicant_full_name
			applicant_phone: $applicant_phone
			missing_full_name: $missing_full_name
			missing_gender: $missing_gender
			missing_date: $missing_date
			search_area_type: $search_area_type
			missing_health: $missing_health
			missing_special_features: $missing_special_features
			missing_dob: $missing_dob
			missing_region: $missing_region
			additional_area_of_search: $additional_area_of_search
			missing_phone: $missing_phone
			missing_address: $missing_address
			missing_time: $missing_time
			police_report: $police_report
			circumstances_of_missing: $circumstances_of_missing
			missing_clothes: $missing_clothes
			missing_carry_item: $missing_carry_item
			additional_info: $additional_info
			family_contacts: $family_contacts
			upload_photo: $upload_photo
		) {
			... on MissingPeople {
				applicant_full_name
				applicant_phone
				missing_full_name
				missing_gender
				missing_dob
				missing_region
				additional_area_of_search
				missing_phone
				missing_address
				missing_date
				missing_time
				police_report
				search_area_type
				circumstances_of_missing
				missing_health
				missing_clothes
				missing_special_features
				missing_carry_item
				additional_info
				family_contacts
				upload_photo
			}
			... on ValidationErrorsList {
				errors {
					field
					messages
				}
			}
		}
	}
}
